language: node_js
os: linux
dist: xenial
node_js:
  - "14"

cache:
   directories:
      - node_modules
      - $HOME/.meteor/

before_install:
   - npm install -g spacejam
   - curl https://install.meteor.com | /bin/sh
before_script:
  - npm install
script: 
  - spacejam test-packages ./ --driver-package=practicalmeteor:mocha-console-runner

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
